### ISSUE TITLE
Lookup error on __init__ method

### ISSUE THREAD

**Issue by mofeing** [wesselb/plum#39]
I have several different constructors of a class based on its types, so I decided to dispatch them. For example I have the following method:

```python
class BlockArray:
    @dispatch
    def __init__(self, blocks: List[Array], grid: Sequence[int]):
        pass

data = [np.zeros(1)]
grid = (1,)
arr = BlockArray(data, grid)
```

But this gives the following error:
```
...
.venv/lib/python3.8/site-packages/plum/parametric.py:65: in __call__
    type_parameter = cls.__infer_type_parameter__(*args, **kw_args)
plum/function.py:226: in plum.function.ClassFunction.__call__
    ???
plum/function.py:536: in plum.function.Function.__call__
    ???
plum/function.py:498: in plum.function.Function.resolve_method
    ???
plum/function.py:464: in plum.function.Function.resolve_method
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   plum.function.NotFoundLookupError: For function "__infer_type_parameter__" of rosnet.array.block.BlockArray, signature Signature(plum.parametric.CovariantMeta, List[numpy.ndarray], Tuple[builtins.int, builtins.int, builtins.int]) could not be resolved.

plum/function.py:435: NotFoundLookupError
```

I've tried changing the type annotations but nothing. Problem seems to be in the `self` argument. If I otherwise cal `__init__` directly like this, `plum` correctly dispatches the method. 
```python
class mock: pass
arr = mock()
arr.data = None
BlockArray.__init__(arr, data, grid)
```

**Comment by PhilipVinc** [comment]
Did you decorate something with `@parametric` by any chance?

**Comment by mofeing** [comment]
Okay, I solved it by renaming the constructors to `__init` and making the `__init__` call the dispatched method.

```python
class BlockArray:
    def __init__(self, *args, **kwargs):
        self.__init(*args, **kwargs)
    ...
```

Maybe a note in the readme would useful.

**Comment by mofeing** [comment]
I've been trying to replicate the error but it looks like the `__init__` was not the error. Now it seems it breaks on the lookup of a Protocol as a parameter.

```python
from typing import List, Tuple, Protocol, runtime_checkable
from plum import dispatch, parametric
import numpy as np

@runtime_checkable
class Array(Protocol):
    def __array__(self) -> np.ndarray:
        pass


@parametric
class A:
    @dispatch
    def __init__(self, a: List[int]):
        print("list")

    @dispatch
    def __init__(self, a: Tuple[int]):
        print("tuple")

    @dispatch
    def __init__(self: List[Array]):
        print("list of array")

    @classmethod
    def __infer_type_parameter__(cls, *args, **kwargs):
        return object

# ok
assert issubclass(np.ndarray, Array)

# ok
A((1,))

# ok
A([1])

# NotFoundLookupError
A([np.zeros(1)])
```

Error log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plum/function.py", line 587, in plum.function._BoundFunction.__call__
  File "plum/function.py", line 536, in plum.function.Function.__call__
  File "plum/function.py", line 493, in plum.function.Function.resolve_method
  File "plum/function.py", line 464, in plum.function.Function.resolve_method
  File "plum/function.py", line 435, in plum.function.Function.resolve_signature
plum.function.NotFoundLookupError: For function "__init__" of __main__.A, signature Signature(__main__.A, List[numpy.ndarray]) could not be resolved.
```

should i open a new issue or change the title of this?

**Comment by mofeing** [comment]
Okay, I just noticed that `plum` does not support Protocols yet #28  🤦‍♂️

I will close this.
