### ISSUE TITLE
Issue when the output is the a Generator

### ISSUE THREAD

**Issue by xiki-tempula** [wesselb/plum#48]
It seems that the plum has issue in dispatch function when the output is Generator

I have the sample code as
```
from typing import Generator, List
from plum import dispatch
class Convert():
    @dispatch
    def run(self, input: List[int, ]) -> Generator[int, None, None]:
        for item in input:
            yield int(item)

    @dispatch
    def run(self, input: List[float, ]) -> Generator[float, None, None]:
        for item in input:
            yield float(item)
```

I got
```
Traceback (most recent call last):
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-2a8843a2d5ae>", line 1, in <module>
    class Convert():
  File "<ipython-input-26-2a8843a2d5ae>", line 3, in Convert
    def run(self, input: List[int, ]) -> Generator[int, None, None]:
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/plum/dispatcher.py", line 43, in __call__
    signature, return_type = extract_signature(method)
  File "plum/function.py", line 120, in plum.function.extract_signature
  File "/Users/zwu/miniconda3_x86/envs/exs-orionbssfloes/lib/python3.7/site-packages/plum/type.py", line 409, in ptype
    f'There is currently no support for "{obj}". '
NotImplementedError: There is currently no support for "typing.Generator[int, NoneType, NoneType]". Please open an issue at https://github.com/wesselb/plum/issues
```

**Comment by wesselb** [comment]
Hey @xiki-tempula! Thanks for opening an issue for this. Generator types are indeed not yet supported. Unfortunately, I do not have the bandwidth to this on right now, but I'll put it on the TODO list to get to soon. :)

**Comment by xiki-tempula** [comment]
@wesselb Thank you.
